version: "3.7"

services:
  mongolidentity:
    container_name: mongolidentity
    image: mongolidentity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3002:80"
    restart: always
